### ISSUE TITLE
Snapshot Internal Error

### ISSUE THREAD

**Issue by khanhibus** [pganalyze/collector#224] opened 2021-12-09 17:55 UTC
Hello,

On 2 of our servers, we've been getting snapshot errors, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/11794738/145449518-ddd5e122-11c5-4018-a488-f51f5285f5a2.png)

The snapshots are successfully submitted but are not able to be processed.

This appears to have started after upgrading to pganalyze release 2021.12.0. I can confirm that the 2 servers where this is failing on are running pganalyze-collector 0.41.2.

Any suggestions to fix this issue? I should also mention that we are running the on-prem version of pganalyze with no internet connectivity.

**Comment by lfittl** [comment] 2021-12-09 19:22
@khanhibus It would be best if you open a support ticket on this (by emailing support@pganalyze.com), then we can investigate what the root cause might be.

Closing this here as its unlikely to be related to the collector itself (since this error appears to be within the pganalyze app / processing logic).

**Closed by lfittl** 2021-12-09 19:22 UTC
