### ISSUE TITLE
RDS docker monitoring section in README.md not working as expected

### ISSUE THREAD

**Issue by steinnes** [pganalyze/collector#201] opened 2021-10-12 11:26 UTC
I was updating my pganalyze collector configuration which pulls data from our RDS instance, and ran into an SSL issue (`Could not collect query stats for server: failed to connect to database: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0`).

Rather than go down that rabbit hole I decided to see whether using the latest docker from this repository would do the trick, so I did as instructed in the README here:
![image](https://user-images.githubusercontent.com/1097582/136946510-918e9d88-416c-4e4d-b7bc-b091a280f581.png)

This however resulted in my collector attempting only to connect to a local database instance:
```
2021/10/12 11:17:10 E [default] Could not process server: Failed to connect to database: dial tcp 127.0.0.1:5432: connect: connection refused
```

I went back to the pganalyze.com documentation and noticed that the nice `DB_URL` environment variable mentioned in the README here was not used, but rather a set of environment variables (DB_HOST, DB_
![image](https://user-images.githubusercontent.com/1097582/136946471-86677c27-171e-4809-a97b-8e97e3aea885.png)

Using the set of environment variables worked fine.  I suspect the README.md here is inaccurate.

**Comment by lfittl** [comment] 2021-11-17 23:27
@steinnes Thats odd - `DB_URL` is certainly supported, although the README.md hasn't been updated in a while.

I'll close this since I don't see anything obviously wrong with the README example, but in case thats reproducible still feel free to open a ticket so we can discuss this in more detail with the specific settings to review if there is something wrong.

**Closed by lfittl** 2021-11-17 23:27 UTC
