### ISSUE TITLE
Can't use the collector when there is a hash (#) in the password

### ISSUE THREAD

**Issue by shamil** [pganalyze/collector#124] opened 2020-12-15 12:46 UTC
I guess it treat everything after hash as comment.

**Comment by uhoh-itsmaciek** [comment] 2020-12-17 00:02
Hi @shamil--thanks for the report. Have you tried escaping the hash in the password value with a backslash, or quoting the entire value?

**Comment by caleb15** [comment] 2020-12-22 21:02
I ran into this too - see https://github.com/pganalyze/collector/issues/132

**Comment by uhoh-itsmaciek** [comment] 2020-12-22 23:16
@caleb15 oh wow, it definitely shouldn't segfault. I only suggested quoting or escaping because a hash is a `.ini` comment character, so I assumed the hash and everything after were being ignored, leading to a different password. Are you setting the password via `db_password` or `db_url`?

**Comment by uhoh-itsmaciek** [comment] 2020-12-22 23:31
So I tried this myself with db_url and I was able to reproduce the crash. The hash character is treated as a comment by https://github.com/go-ini/ini, which we use for parsing the config file, and the resulting invalid URL fails to parse, and we're not doing proper error-checking regarding valid URLs. Unfortunately, it looks like the quoting and escaping suggestions I made earlier do *not* solve this--looks like go-ini does not handle this correctly: https://github.com/go-ini/ini/issues/277 https://github.com/go-ini/ini/issues/187 .

**Comment by uhoh-itsmaciek** [comment] 2020-12-28 20:14
We have a fix in progress for the error handling in #133 to avoid the crash and allow `#` in values, but the root cause here is that the character is reserved in URLs (since it delineates the start of the fragment), so it must be URL-encoded as `%23`. Could you please try that @caleb15 @shamil? That should work even in current collector versions.

**Comment by uhoh-itsmaciek** [comment] 2021-01-15 23:32
Closing since #133 should fix this; please reopen if there are still issues.

**Closed by uhoh-itsmaciek** 2021-01-15 23:32 UTC

**Comment by caleb15** [comment] 2021-01-18 17:23
I'm using db_url. I fixed it by removing the hash.
